### ISSUE TITLE
Obsolete ThinPlateSplines dependency in Notebooks directory?

### ISSUE THREAD

**Issue by wkearn** [vishwas1984/LaplaceInterpolation.jl#4]
ThinPlateSplines.jl is required in the Notebooks Project.toml, but it is unregistered, so instantiation fails even after #3 is fixed, but it looks like the example notebooks don't actually require ThinPlateSplines, so it might be possible just to remove it. Otherwise it will also need an entry in the Manifest.toml file as described in #3.

**Comment by vishwas1984** [comment]
I have removed the ThinPlateSplines dependency.

**Comment by vishwas1984** [comment]
ThinPlateSplines is no longer in Notebooks/Project.toml (https://github.com/vishwas1984/LaplaceInterpolation.jl/blob/master/Notebooks/Project.toml)
